#!/bin/bash
set -e

BASE_NAME=$1

#SCRIPT="`dirname $0`/jetbrains/$BASE_NAME"
SCRIPT="$HOME/.local/share/JetBrains/Toolbox/scripts/$BASE_NAME"
PARAMS="$2"

if [ -z "$PARAMS" ]
then
  PARAMS=`pwd`
fi

echo "starting $BASE_NAME..."

#call launcher
$SCRIPT $PARAMS &>/dev/null &

#detache child process
disown
